#!/bin/bash
# ═══════════════════════════════════════════════════════════
# Maxwellian Unity Environment Setup
# ═══════════════════════════════════════════════════════════
# Purpose: Configure shell environment for Unity Energy Maxwellians
# Usage: ./setup_maxwellian_env.sh
# Author: Unity Energy Team
# Date: 2026-01-23
# ═══════════════════════════════════════════════════════════

set -e  # Exit on error

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
UNITY_ROOT="$SCRIPT_DIR"

echo "════════════════════════════════════════════════════════"
echo "  Maxwellian Unity Environment Setup"
echo "════════════════════════════════════════════════════════"
echo ""

# ───────────────────────────────────────────────────────────
# 1. Verify Directory Structure
# ───────────────────────────────────────────────────────────
echo "→ Verifying Unity directory structure..."

REQUIRED_DIRS=(
    "$UNITY_ROOT/Library"
    "$UNITY_ROOT/Memory"
    "$UNITY_ROOT/Memory/local"
    "$UNITY_ROOT/Memory/local/crash_recovery"
    "$UNITY_ROOT/Team"
    "$UNITY_ROOT/Products"
)

for dir in "${REQUIRED_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo "  ✓ Creating: $dir"
        mkdir -p "$dir"
    else
        echo "  ✓ Exists: $dir"
    fi
done

echo ""

# ───────────────────────────────────────────────────────────
# 2. Create Maxwellian Shell Configuration
# ───────────────────────────────────────────────────────────
echo "→ Creating Maxwellian shell configuration..."

MAXWELLIAN_RC="$UNITY_ROOT/.maxwellian_rc"

cat > "$MAXWELLIAN_RC" << 'EOF'
# ═══════════════════════════════════════════════════════════
# Maxwellian Unity Environment Configuration
# Auto-generated by setup_maxwellian_env.sh
# Source this file from your .zshrc or .bashrc
# ═══════════════════════════════════════════════════════════

# Determine Unity root (where this file lives)
MAXWELLIAN_RC_PATH="${(%):-%x}"  # zsh
[ -z "$MAXWELLIAN_RC_PATH" ] && MAXWELLIAN_RC_PATH="${BASH_SOURCE[0]}"  # bash
UNITY_ROOT="$(cd "$(dirname "$MAXWELLIAN_RC_PATH")" && pwd)"

# ───────────────────────────────────────────────────────────
# Maxwell Library & Memory Paths
# ───────────────────────────────────────────────────────────
# LIBRARY: Long-term knowledge base, documents, references
# MEMORY: Short-term session data, context, working memory

export MAXWELL_LIBRARY="$UNITY_ROOT/Library"
export MAXWELL_MEMORY="$UNITY_ROOT/Memory"
export MAXWELLIAN_LIBRARY="$UNITY_ROOT/Library"
export MAXWELLIAN_MEMORY="$UNITY_ROOT/Memory"

# ───────────────────────────────────────────────────────────
# Convenience Symlinks
# ───────────────────────────────────────────────────────────
# Create ~/eMemory symlink if it doesn't exist
if [ ! -L "$HOME/eMemory" ]; then
    rm -f "$HOME/eMemory" 2>/dev/null  # Remove broken symlink if exists
    ln -s "$MAXWELL_MEMORY" "$HOME/eMemory" 2>/dev/null && \
        echo "  ✓ Created symlink: ~/eMemory → $MAXWELL_MEMORY"
fi

# ───────────────────────────────────────────────────────────
# Crash Recovery - Warp Session Backup
# ───────────────────────────────────────────────────────────
# Automatically saves shell history on startup for crash recovery

CRASH_RECOVERY_DIR="$MAXWELL_MEMORY/local/crash_recovery"
mkdir -p "$CRASH_RECOVERY_DIR" 2>/dev/null

# Create timestamped backup of shell history
if [ -f "$HOME/.zsh_history" ]; then
    TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    cp "$HOME/.zsh_history" "$CRASH_RECOVERY_DIR/zsh_history_${TIMESTAMP}.bak" 2>/dev/null
    
    # Keep only last 30 backups (prevent directory bloat)
    ls -t "$CRASH_RECOVERY_DIR"/zsh_history_*.bak 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null
fi

# ───────────────────────────────────────────────────────────
# Maxwellian Aliases
# ───────────────────────────────────────────────────────────
alias cdlibrary="cd \$MAXWELL_LIBRARY"     # Go to Library
alias cdmemory="cd \$MAXWELL_MEMORY"       # Go to Memory
alias cdemem="cd \$MAXWELL_MEMORY"         # Go to Memory (short)

# ═══════════════════════════════════════════════════════════
# END Maxwellian Unity Configuration
# ═══════════════════════════════════════════════════════════
EOF

echo "  ✓ Created: $MAXWELLIAN_RC"
echo ""

# ───────────────────────────────────────────────────────────
# 3. Update User's .zshrc
# ───────────────────────────────────────────────────────────
echo "→ Configuring shell integration..."

ZSHRC="$HOME/.zshrc"
SOURCE_LINE="source \"$MAXWELLIAN_RC\""

# Check if already sourced
if grep -q "source.*\.maxwellian_rc" "$ZSHRC" 2>/dev/null; then
    echo "  ✓ Already configured in ~/.zshrc"
else
    echo ""
    echo "  Adding Maxwellian configuration to ~/.zshrc"
    echo ""
    cat >> "$ZSHRC" << EOF

# ═══════════════════════════════════════════════════════════
# Maxwellian Unity Environment
# ═══════════════════════════════════════════════════════════
$SOURCE_LINE
EOF
    echo "  ✓ Updated ~/.zshrc"
fi

echo ""

# ───────────────────────────────────────────────────────────
# 4. Create eMemory Symlink
# ───────────────────────────────────────────────────────────
echo "→ Creating convenience symlinks..."

if [ -L "$HOME/eMemory" ]; then
    CURRENT_TARGET=$(readlink "$HOME/eMemory")
    if [ "$CURRENT_TARGET" != "$UNITY_ROOT/Memory" ]; then
        rm -f "$HOME/eMemory"
        ln -s "$UNITY_ROOT/Memory" "$HOME/eMemory"
        echo "  ✓ Updated: ~/eMemory → Memory"
    else
        echo "  ✓ Already exists: ~/eMemory"
    fi
else
    ln -s "$UNITY_ROOT/Memory" "$HOME/eMemory"
    echo "  ✓ Created: ~/eMemory → Memory"
fi

echo ""

# ───────────────────────────────────────────────────────────
# 5. Summary
# ───────────────────────────────────────────────────────────
echo "════════════════════════════════════════════════════════"
echo "  ✅ Maxwellian Unity Environment Setup Complete!"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Environment Variables:"
echo "  MAXWELL_LIBRARY  → $UNITY_ROOT/Library"
echo "  MAXWELL_MEMORY   → $UNITY_ROOT/Memory"
echo ""
echo "Shortcuts:"
echo "  ~/eMemory        → $UNITY_ROOT/Memory"
echo ""
echo "Aliases:"
echo "  cdlibrary        → cd to Library"
echo "  cdmemory         → cd to Memory"
echo ""
echo "Next Steps:"
echo "  1. Restart your terminal (or run: source ~/.zshrc)"
echo "  2. Test with: echo \$MAXWELL_LIBRARY"
echo "  3. Test with: ls ~/eMemory"
echo ""
echo "════════════════════════════════════════════════════════"
